"""add missing education_requirement column to roles

Revision ID: 44957f3a751a
Revises: 403697dc9be3
Create Date: 2026-08-24 00:56:15.741132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44957f3a751a'
down_revision = '403697dc9be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.alter_column('expected_answer',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('interview_responses', schema=None) as batch_op:
        batch_op.alter_column('answer_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('resume_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=4294967295),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_requirement', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('education_requirement')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('resume_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('interview_responses', schema=None) as batch_op:
        batch_op.alter_column('answer_text',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.alter_column('expected_answer',
               existing_type=sa.Text(length=4294967295),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
